language: c
script: ./travis-tool.sh run_tests
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh r_binary_install rgl RANN igraph filehash digest testthat bigmemory ff
  - ./travis-tool.sh install_github jefferis/nat
install:
  - ./travis-tool.sh install_deps
  - sh -e /etc/init.d/xvfb start
notifications:
  email:
    on_success: change
    on_failure: change
env:
  - global:
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
    - DISPLAY=:99.0
after_failure:
  - cat /home/travis/build/ajdm/flycircuit/flycircuit.Rcheck/00check.log
